Add Migrant Issue Shelter Map
chicagomaroon/data-visualizations pull request #55
Opened 2024-01-17 20:04 UTC by Asteinhart

## What does this PR do?
adds a map using mapbox for the migrant issue stories. followed an example [here](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/).
 
pulled data from map embded on [New Arrivals Data Dashboard](https://40thward.org/cirr/new-arrivals/new-arrivals-data-dashboard/). @vernonli1 took KML file (in folder as `shelters.kml`) to convert to geopandas frame and I did some additional light cleaning and converted to geojson for mapbox all in `shelters.ipynb` file. will probably need to move these somewhere else for better organization. 

## How was the functionality tested and verified?
All steps should be completed in the order presented, and you should not move on to the next step until the previous is completed.
- [ ] The title of the `html` page is the same as the chart.
- [ ] The `meta_data.json` file is filled in correctly (the description is a complete sentence, the title is the same as the visual).
- [ ] The chart and its associated pages have been minified using the `npm run process-visual` command.
- [ ] The visual is styled similar to other charts (centered title/subtitle, no legends unless absolutely necessary, etc.)
- [ ] This visual was approved by the lead developer.
- [ ] The visual was approved by the story's stakeholders.

2024-01-17 20:14 UTC, michplunkett commented
I'll need you to update the branch before I can look at it.

2024-01-30 04:16 UTC, michplunkett commented on 2024/migrant-issue-map/meta_data.json
> +    "description": "A map of all current shelters according the city of Chicago",
Turn this into a standard sentence structure.

2024-01-30 04:20 UTC, michplunkett commented on 2024/migrant-issue-map/index.html
> +        <script src="https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.js"></script>
Add `type="text/javascript"` to this.

2024-01-30 04:20 UTC, michplunkett commented on 2024/migrant-issue-map/index.html
> +            }
Move this CSS to the inline spot a couple lines up.

2024-01-30 04:23 UTC, michplunkett requested changes
Great work! We discussed some issues with MapBox, they still apply here. Is there another package you can do this with? In this PR https://github.com/chicagomaroon/data-visualizations/pull/50 you have the Jupyter notebook in the `data_analysis` folder, I'd like you to add this notebook to that folder as well.

2024-01-30 04:47 UTC, Asteinhart commented
> Great work! We discussed some issues with MapBox, they still apply here. Is there another package you can do this with? In this PR #50 you have the Jupyter notebook in the `data_analysis` folder, I'd like you to add this notebook to that folder as well.

Ya going to move this over to leaflet as well!

2024-03-27 02:43 UTC, michplunkett approved these changes

2024-03-27 02:45 UTC, Nik4002 approved these changes
Looks good!

2024-03-27 02:46 UTC, merged