Classof2024 tl
chicagomaroon/data-visualizations pull request #78
Opened 2024-04-26 02:14 UTC by tiffanyl9

Add Grad Issue class of 2024 charts.

## What does this PR do?
Add Grad Issue Class of 2024 pie (employment by industry) and bar (employment vs. continuing education) charts.

## How was the functionality tested and verified?
All steps should be completed in the order presented, and you should not move on to the next step until the previous is completed.
- [ ] The title of the `html` page is the same as the chart.
- [ ] The `meta_data.json` file is filled in correctly (the description is a complete sentence, the title is the same as the visual).
- [ ] The chart and its associated pages have been minified using the `npm run process-visual` command.
- [ ] The visual is styled similar to other charts (centered title/subtitle, no legends unless absolutely necessary, etc.)
- [ ] This visual was approved by the lead developer.
- [ ] The visual was approved by the story's stakeholders.

2024-04-26 05:15 UTC, michplunkett commented on 2024/classof2024_ed_vs_empl/main.js
> +    },
The title and subtitle should be centered.

2024-04-26 05:15 UTC, michplunkett commented on 2024/classof2024_tl/main.js
> +    },
Same with these two.

2024-04-26 05:16 UTC, michplunkett commented on 2024/classof2024_tl/index.html
> +        <!-- IF YOU AREN'T USING AN IMPORT, IT'S RECOMMENDED THAT YOU REMOVE IT -->
Do you need all of these imports? Same for the other visual.

2024-04-26 05:17 UTC, michplunkett commented
Update the title when you can to something like `Add class of 2024 visuals`.

2024-04-26 06:17 UTC, Nik4002 commented
A few things:
1. About the bar chart, if you think my comment about flipping the colors makes sense, then do that
2. Don't forget to minify the files when you're done

Otherwise, looks good to me!

2024-04-26 19:40 UTC, michplunkett requested changes
Specifically the title things and removing any unused highcharts modules.

2024-04-27 04:25 UTC, Nik4002 commented
Just to clarify, @asteinhart, we decided that you will just screenshot the map and publish it that way? Also, about the subtitle, I feel like that sentence might be better in the plot caption.

2024-04-27 22:48 UTC, michplunkett approved these changes

2024-04-28 03:36 UTC, merged